src/Entity/StudentInfo.php
<?php

namespace App\Entity;

use App\Repository\StudentInfoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentInfoRepository::class)]
class StudentInfo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phone_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_of_birth = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $preferred_name = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?LearningStyle $learning_style = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?Neurodiversity $neurodiversity = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?Gender $gender = null;

    #[ORM\Column(length: 255)]
    private ?string $ethnicity = null;

    #[ORM\Column]
    private ?bool $nz_citizen = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?PaymentStatus $payment_status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getPreferredName(): ?string
    {
        return $this->preferred_name;
    }

    public function setPreferredName(?string $preferred_name): static
    {
        $this->preferred_name = $preferred_name;

        return $this;
    }

    public function getLearningStyle(): ?LearningStyle
    {
        return $this->learning_style;
    }

    public function setLearningStyle(?LearningStyle $learning_style): static
    {
        $this->learning_style = $learning_style;

        return $this;
    }

    public function getNeurodiversity(): ?Neurodiversity
    {
        return $this->neurodiversity;
    }

    public function setNeurodiversity(?Neurodiversity $neurodiversity): static
    {
        $this->neurodiversity = $neurodiversity;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getEthnicity(): ?string
    {
        return $this->ethnicity;
    }

    public function setEthnicity(string $ethnicity): static
    {
        $this->ethnicity = $ethnicity;

        return $this;
    }

    public function isNzCitizen(): ?bool
    {
        return $this->nz_citizen;
    }

    public function setNzCitizen(bool $nz_citizen): static
    {
        $this->nz_citizen = $nz_citizen;

        return $this;
    }

    public function getPaymentStatus(): ?PaymentStatus
    {
        return $this->payment_status;
    }

    public function setPaymentStatus(?PaymentStatus $payment_status): static
    {
        $this->payment_status = $payment_status;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity('email', 'Email already taken')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 1500, nullable: true)]
    private ?string $profile_pic = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getProfilePic(): ?string
    {
        return $this->profile_pic;
    }

    public function setProfilePic(?string $profile_pic): static
    {
        $this->profile_pic = $profile_pic;

        return $this;
    }
}

templates/_partials/_footer.html.twig
<footer class="footer position-relative bottom border-top mt-2">
    <p class="ms-2">Made with <i class="fa-solid fa-heart" style="color:red"></i> by Silvestre @ SELMA</p>
</footer>

templates/_partials/_header.html.twig
<div class="d-block d-sm-none sticky-top border-bottom" id="small-screen-header" style="background-color: #fff; height: 40px; width: 430px;">
    {% if is_granted('ROLE_USER') %}
        <div class="dropdown">
            <a href="#" class="nav-link" role="button" data-bs-toggle="dropdown" id="small-screen-dropdown">
                <i class="fa-solid fa-bars"></i>
            </a>
            <div class="dropdown-menu mt-1" id="dropdown">
                <a href="{{ path('app_main') }}" class="dropdown-item" disabled>Homepage</a>
                <a href="{{ path('displayAllStudents') }}" class="dropdown-item" disabled>Student Index</a>
                <a href="{{ path('new_student') }}" class="dropdown-item" disabled>New Student</a>
                <a href="{{ path('app_chart') }}" class="dropdown-item" disabled>Dashboard</a>
                <a href="{{ path('app_logout') }}" class="dropdown-item border-top" disabled>Logout</a>
            </div>
        </div>
    {% else %}
    <div class="dropdown">
        <a href="#" class="nav-link" role="button" data-bs-toggle="dropdown" id="small-screen-dropdown">
            <i class="fa-solid fa-bars"></i>
        </a>
        <div class="dropdown-menu mt-1" id="dropdown">
            <a href="{{ path('app_login') }}" class="dropdown-item">Log In</a>
            <a href="{{ path('sign-up') }}" class="dropdown-item">Sign Up</a>
        </div>
    </div>
    {% endif %}
</div>

<div class="w-100 d-flex border-bottom sticky-top d-lg-flex d-none" id="header-container" style="background-color: #fff; height: 40px">
        {% if is_granted('ROLE_USER') %}
    <a href="/"><i class="fa-solid fa-house" style="color: var(--selma-blue)"></i></a>
    <nav class="header mx-auto d-flex flex-row justify-content-lg-between h-25" id="header">
        <div id="left-side-header" class="ms-3 d-flex flex-row mt-3 justify-content-center">
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="btn1">
                    <i class="fa-solid fa-align-center"></i> Curriculum
                </a>
                <div class="dropdown-menu mt-2" id="dropdown">
                    <a href="#" class="dropdown-item" disabled>Curriculum Index</a>
                    <a href="#" class="dropdown-item" disabled>New Programme</a>
                    <a href="#" class="dropdown-item" disabled>New Component</a>
                    <a href="#" class="dropdown-item" disabled>Training.gov.au</a>
                    <a href="#" class="dropdown-item border-top" disabled>Grading Schemes</a>
                </div>
            </div>
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="btn1">
                    <i class="fa-solid fa-user-secret"></i> Students
                </a>
                <div class="dropdown-menu mt-2" id="dropdown">
                    <a href="{{ path('displayAllStudents') }}" class="dropdown-item">Student Index</a>
                    <a href="{{ path('new_student') }}" class="dropdown-item">New Student</a>
                    <a href="#" class="dropdown-item" disabled>Merge Students</a>
                    <a href="#" class="dropdown-item border" disabled>Form Submissions</a>
                    <a href="#" class="dropdown-item" disabled>Contacts</a>
                    <a href="#" class="dropdown-item" disabled>Organizations</a>
                </div>
            </div>
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="btn1">
                    <i class="fa-solid fa-user-group"></i> Cohorts
                </a>
                <div class="dropdown-menu mt-2" id="dropdown">
                    <a href="#" class="dropdown-item">Intake Index</a>
                    <a href="#" class="dropdown-item">New Intake</a>
                    <a href="#" class="dropdown-item">Clone Intake</a>
                    <a href="#" class="dropdown-item border-top">Class Index</a>
                    <a href="#" class="dropdown-item">New Class</a>

                </div>
            </div>
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="btn1">
                    <i class="fa-solid fa-graduation-cap"></i> Enrolments
                </a>
                <div class="dropdown-menu mt-2" id="dropdown">
                    <a href="#" class="dropdown-item">Enrolment Index</a>
                    <a href="#" class="dropdown-item">Enrol Students</a>
                    <a href="#" class="dropdown-item border">Marking</a>
                    <a href="#" class="dropdown-item">Price Books</a>
                    <a href="#" class="dropdown-item">Invoices</a>

                </div>
            </div>
            <div class="dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="btn1">
                    <i class="fa-solid fa-chart-line"></i> Reports
                </a>
                <div class="dropdown-menu mt-2" id="dropdown">
                    <a href="#" class="dropdown-item">Enrolment Index</a>
                    <a href="#" class="dropdown-item">Enrol Students</a>
                    <a href="#" class="dropdown-item border-top border-bottom">Marking</a>
                    <a href="#" class="dropdown-item">Price Books</a>
                    <a href="#" class="dropdown-item">Invoices</a>
                    <a href="{{ path('app_chart') }}" class="dropdown-item">Charts</a>

                </div>
            </div>
            <a href="{{ path('app_chart') }}" class="text-decoration-none" id="dashboard"><i class="fa-solid fa-ghost"></i> Dashboard</a>
        </div>

        <div id="right-side-header" class="me-3 mt-3 d-flex flex-row">
            <input type="search" class="border-none" placeholder="Search Students...">
            <a href="#" class="me-3 right-side-nav-icons"><i class="fa-solid fa-sun" style="color: #ffaa01;"></i></a>
            <a href="#" class="me-3 right-side-nav-icons"><i class="fa-solid fa-globe" style="color: var(--header-text-color);"></i></a>
            <a href="#" class="me-3 right-side-nav-icons" data-bs-toggle="offcanvas" data-bs-target="#menuOffcanvas"><i class="fa-solid fa-gear" style="color: var(--header-text-color);"></i></a>

            <div class="offcanvas offcanvas-end" tabindex="-1" id="menuOffcanvas">
                <div class="offcanvas-header border-bottom">
                    <h5 class="offcanvas-title">Settings</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="list-group list-group-flush" style="width: 90%; font-size: 14px; font-family: Poppins, serif;">
                        <a href="#" class="list-group-item border-0">Account</a>
                        <a href="#" class="list-group-item border-0">Campus Index</a>
                        <hr class="my-2">
                        <a href="#" class="list-group-item border-0">Communication</a>
                        <a href="#" class="list-group-item border-0">Timetable/Attendance</a>
                        <a href="#" class="list-group-item border-0">Lookup Data</a>
                        <a href="#" class="list-group-item border-0">Custom Fields</a>
                        <a href="#" class="list-group-item border-0">Tag Manager</a>
                        <a href="#" class="list-group-item border-0">Validation Manager</a>
                        <a href="#" class="list-group-item border-0">Form Manager</a>
                        <a href="#" class="list-group-item border-0">Integrations</a>
                        <a href="#" class="list-group-item border-0">Scheduler</a>
                        <a href="#" class="list-group-item border-0">Compliance</a>
                        <hr class="my-2">
                        <a href="#" class="list-group-item border-0">System Users</a>
                        {% if is_granted('ROLE_REGISTRAR') %}
                        <a href="{{ path('admin_users_list') }}" class="list-group-item border-0">Roles and Permissions</a>
                        {% endif %}
                        <hr class="my-2">
                        <a href="#" class="list-group-item border-0">API</a>
                    </div>
                </div>
            </div>

            <div class="dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="btn2">
                    <i class="fa-solid fa-user-ninja" id="ninja-icon"></i>  Silvestre
                </a>
                <div class="dropdown-menu mt-2" id="dropdown">
                    <a href="#" class="dropdown-item">Profile</a>
                    <a href="#" class="dropdown-item">My Calendar</a>
                    <a href="#" class="dropdown-item">Password/Security</a>
                    <a href="#" class="dropdown-item">User Manual</a>
                    <a href="#" class="dropdown-item">Support</a>
                    <a href="{{ path('app_logout') }}" class="dropdown-item">Logout</a>
                </div>
            </div>
        </div>
        {% else %}
            <div class="ms-auto me-3 mt-2" id="login-signup-links-header">
                <a href="{{ path('app_login') }}" class="text-decoration-none me-3" style="color: var(--header-text-color);">Login</a>
                <a href="{{ path('sign-up') }}" class="text-decoration-none" style="color: var(--header-text-color);">Sign Up</a>
            </div>
        {% endif %}
    </nav>
</div>

templates/_partials/_invoiceCard.html.twig
<div class="card mb-2" style="width: 48%;">
    <div class="card-header">Payment by Status</div>
    <div class="card-body">
        <div class="d-flex flex-row justify-content-between mt-3" style="width: 80%; height: 50%;">
            <a href="#" class="text-decoration-none invoice-card-span">
            <span class="d-flex flex-column">
                <i class="fa-solid fa-pencil text-center fa-2x mt-1" style="color: var(--selma-blue);"></i>
                <p class="text-center" style="color: var(--header-text-color)">
                    Drafts ({{ paymentStatus['Draft'] }})
                </p>
            </span>
            </a>

            <a href="#" class="text-decoration-none invoice-card-span">
                <span class="d-flex flex-column">
                <i class="fa-solid fa-file-invoice text-center fa-2x mt-1" style="color: lightgreen;"></i>
                <p class="text-center" style="color: var(--header-text-color)">
                    Invoiced ({{ paymentStatus['Invoiced'] }})
                </p>
            </span>
            </a>

            <a href="#" class="text-decoration-none invoice-card-span">
            <span class="d-flex flex-column">
                <i class="fa-solid fa-circle-exclamation fa-2x text-danger text-center mt-1"></i>
                <p class="text-center" style="color: var(--header-text-color)">
                    Overdue ({{ paymentStatus['Overdue'] }})
                </p>
            </span>
            </a>
        </div>
        <div class="d-flex flex-column invoice-info-div" style="height: 40%; font-size: 12px;">
            <p><strong>Students:</strong> {{ students|length }}</p>
            <p><strong style="color: var(--selma-blue)">Drafts:</strong> {{ paymentStatus['Draft'] }}</p>
            <p><strong style="color: lightgreen;">Invoiced:</strong> {{ paymentStatus['Invoiced'] }}</p>
            <p><strong class="text-danger">Overdue:</strong> {{ paymentStatus['Overdue'] }}</p>
        </div>
    </div>
    <div class="card-footer">
        See more invoice information <a href="#" class="link-txt-color text-decoration-none">here</a>
    </div>
</div>

templates/_partials/_learningStyleChart.html.twig
<div class="card widget-container" style="height: 400px; width: 48%;">
    <h5 class="card-header border-bottom w-100">Learning Styles</h5>
    <div class="card-body">
        <div class="chart mb-2">
            <canvas id="studentChart"></canvas>
        </div>
    </div>
    <div class="card-footer">Find out more <a href="{{ path('app_display') }}" class="text-decoration-none link-txt-color">here</a></div>
</div>
<script>
    const learningStyles = {{ learningStyles|json_encode|raw }};
    const labels = Object.keys(learningStyles);
    const values = Object.values(learningStyles);

    const ctx = document.getElementById('studentChart').getContext('2d');

    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Learning Styles',
                data: values,
                backgroundColor: [
                    'rgba(155, 199, 132, 0.6)',
                    'rgba(54, 162, 235, 0.6)',
                    'rgba(255, 56, 186, 0.6)',
                    'rgba(75, 192, 192, 0.6)',
                    'rgba(153, 102, 255, 0.6)',
                    'rgba(255, 159, 64, 0.6)',
                    'rgba(255, 99, 132, 0.6)',
                    'rgba(54, 162, 95, 0.6)'
                ],
                borderColor: [
                    'rgba(155, 199, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 56, 186, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 95, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: {
                    beginAtZero: true
                }
            },
            plugins: {
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            const label = context.label || '';
                            const value = context.raw || 0;
                            return `${label}: ${Math.round(value)}`;
                        }
                    }
                }
            },
            onResize: function(chart, size) {
                const legend = chart.options.plugins.legend;
                if (size.width < 600) {
                    legend.display = false;
                } else {
                    legend.display = true;
                }
                chart.update();
            }
        }
    });
</script>

templates/_partials/_myDashboardCard.html.twig
<div class="card" style="width: 100%; height: auto;">
    <h5 class="card-header w-100 border-bottom">My Dashboard</h5>
    <div class="card-body d-flex flex-row justify-content-between" style="height: 120px;">
        <img src="{{ app.user.profilePic }}" style="height: 100%" class="img rounded-circle" alt="profile-picture">
        <div class="d-flex flex-column user-div mt-4" style="width: 25%; height: 80%; font-size: 12px;">
            <p><i class="fa-solid fa-envelope"></i>  {{ app.user.email }}</p>
            <p><i class="fa-solid fa-lock"></i> <a href="#" class="text-decoration-none link-txt-color">Password/Security</a></p>
            <p><i class="fa-solid fa-right-from-bracket"></i><a href="{{ path('app_logout') }}" class="text-decoration-none link-txt-color">  Logout</a></p>
        </div>
        <div class="d-flex flex-column mt-3" style="width: 12%;">
            <span class="dashboard-icon">
            <h2 class="ms-2" style="color: var(--selma-blue)">{{ students|length }}</h2>
            <p style="font-size: 8px;">My Students</p>
            </span>
        </div>
        <div class="d-flex flex-column mt-3" style="width: 12%;">
            <span class="dashboard-icon">
            <h2 class="ms-3 yellow">0</h2>
            <p style="font-size: 8px;" class="ms-1">My Intakes</p>
            </span>
        </div>
        <div class="d-flex flex-column mt-3" style="width: 12%;">
            <span class="dashboard-icon">
            <h2 class="link-txt-color ms-3 purple">0</h2>
            <p style="font-size: 8px;" class="ms-2">My Tasks</p>
            </span>
        </div>
        <div class="d-flex flex-column mt-3" style="width: 12%;">
            <span class="dashboard-icon">
            <h2 class="text-danger ms-3">0</h2>
            <p style="font-size: 8px;">Overdue Tasks</p>
            </span>
        </div>

    </div>
</div>

templates/_partials/_neurodiversityChart.html.twig
<div class="card widget-container" style="height: 300px; width: 48%">
    <h5 class="card-header border-bottom w-100">Neurodiversities</h5>
    <div class="card-body">
        <div class="chart2 ms-2">
            <canvas id="neurodiversityChart"></canvas>
        </div>
    </div>
    <div class="card-footer">Learn more about neurodiversities <a href="https://www.health.harvard.edu/blog/what-is-neurodiversity-202111232645" target="_blank" class="link-txt-color text-decoration-none">here</a></div>
</div>
<script>
    const neuroCtx = document.getElementById('neurodiversityChart').getContext('2d');
    const neurodiversities = {{ neurodiversities|json_encode|raw }};
    const neuroLabels = Object.keys(neurodiversities);
    const neuroValues = Object.values(neurodiversities);
    delete neurodiversities['null'];
    new Chart(neuroCtx, {
        type: 'doughnut',
        data: {
            labels: neuroLabels,
            datasets: [{
                data: neuroValues,
                backgroundColor: [
                    'rgba(75, 192, 192, 0.6)',
                    'rgba(153, 102, 255, 0.6)',
                    'rgba(255, 159, 64, 0.6)',
                    'rgba(255, 99, 132, 0.6)',
                    'rgba(201, 203, 207, 0.6)',
                    'rgba(35, 192, 82, 0.6)'
                ],
                borderColor: [
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(255, 99, 132, 1)',
                    'rgba(201, 203, 207, 1)',
                    'rgba(35, 192, 82, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    display: true,
                    position: 'right'
                },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            const label = context.label || '';
                            const value = context.raw || 0;
                            return `${label}: ${Math.round(value)}`;
                        }
                    }
                }
            },
        }
    });
</script>

templates/_partials/_updateStudentForm.html.twig
<div class="card w-75 mx-auto" id="form-card">
    <h4 class="card-header">Update student information</h4>
    <div class="card-body">
        <form action="{{ path('student_update', {id: student.id}) }}" method="POST" class="ms-2">
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control w-75" id="name" name="name" placeholder="{{ student.name }}">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control w-75" id="email" name="email" placeholder="{{ student.email }}">
            </div>
            <div class="mb-3">
                <label for="date_of_birth" class="form-label">Date of Birth</label>
                <input type="date" class="form-control w-75" id="date_of_birth" name="date_of_birth">
            </div>
            <div class="mb-3">
                <label for="phone_number" class="form-label">Phone Number</label>
                <input type="text" class="form-control w-75" id="phone_number" name="phone_number"  placeholder="{{ student.phoneNumber }}">
            </div>
            <div class="mb-3">
                <label for="learning_style" class="form-label">Learning Style</label>
                <select type="text" class="form-control w-75" id="learning_style" name="learning_style">
                    <option value="Please select" disabled selected>Please Select</option>
                    <option value="None">None</option>
                    <option value="Visual">Visual</option>
                    <option value="Kinesthetic">Kinesthetic</option>
                    <option value="Logical">Logical</option>
                    <option value="Nature">Nature</option>
                    <option value="Solitary">Solitary</option>
                    <option value="Auditory">Auditory</option>
                    <option value="Read/Write">Read/Write</option>
                    <option value="Social">Social</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="neurodiversity" class="form-label">Neurodiversity</label>
                <select type="text" class="form-control w-75" id="neurodiversity" name="neurodiversity">
                    <option value="Please select" disabled selected>Please select</option>
                    <option value="None">None</option>
                    <option value="Autism">Autism</option>
                    <option value="Dyslexia">Dyslexia</option>
                    <option value="Dyspraxia">Dyspraxia</option>
                    <option value="Dyscalculia">Dyscalculia</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary" style="background-color: var(--selma-blue); outline: var(--selma-blue); border-color: var(--selma-blue);">Update Student</button>
        </form>
    </div>
</div>
<div>
</div>