src/Entity/StudentInfo.php
<?php

namespace App\Entity;

use App\Repository\StudentInfoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StudentInfoRepository::class)]
class StudentInfo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $phone_number = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_of_birth = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $preferred_name = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?LearningStyle $learning_style = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?Neurodiversity $neurodiversity = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?Gender $gender = null;

    #[ORM\Column(length: 255)]
    private ?string $ethnicity = null;

    #[ORM\Column]
    private ?bool $nz_citizen = null;

    #[ORM\ManyToOne(inversedBy: 'studentInfos')]
    private ?PaymentStatus $payment_status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): static
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getPreferredName(): ?string
    {
        return $this->preferred_name;
    }

    public function setPreferredName(?string $preferred_name): static
    {
        $this->preferred_name = $preferred_name;

        return $this;
    }

    public function getLearningStyle(): ?LearningStyle
    {
        return $this->learning_style;
    }

    public function setLearningStyle(?LearningStyle $learning_style): static
    {
        $this->learning_style = $learning_style;

        return $this;
    }

    public function getNeurodiversity(): ?Neurodiversity
    {
        return $this->neurodiversity;
    }

    public function setNeurodiversity(?Neurodiversity $neurodiversity): static
    {
        $this->neurodiversity = $neurodiversity;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): static
    {
        $this->gender = $gender;

        return $this;
    }

    public function getEthnicity(): ?string
    {
        return $this->ethnicity;
    }

    public function setEthnicity(string $ethnicity): static
    {
        $this->ethnicity = $ethnicity;

        return $this;
    }

    public function isNzCitizen(): ?bool
    {
        return $this->nz_citizen;
    }

    public function setNzCitizen(bool $nz_citizen): static
    {
        $this->nz_citizen = $nz_citizen;

        return $this;
    }

    public function getPaymentStatus(): ?PaymentStatus
    {
        return $this->payment_status;
    }

    public function setPaymentStatus(?PaymentStatus $payment_status): static
    {
        $this->payment_status = $payment_status;

        return $this;
    }
}

templates/display-students/displayAllStudents.html.twig
{% extends 'base.html.twig' %}

{% block title %} Student Information {% endblock %}

{% block body %}
    {% include '/_partials/_header.html.twig' %}

    <div class="main-container">
        <div id="main-content" class="mx-auto">
            {#    Computer Screen Size        #}
            <div class="card d-lg-flex d-none">
                <div class="card-header">Student Index</div>
                <div class="card-body">
                    <table class="w-100">
                        <thead>
                        <tr class="border-bottom">
                            <th scope="col">Name</th>
                            <th scope="col">Student ID</th>
                            <th scope="col">Preferred Name</th>
                            <th scope="col">Gender</th>
                            <th scope="col">Email</th>
                            <th scope="col">Learning Style(s)</th>
                            <th scope="col">Neurodiversity</th>
                            <th scope="col"></th>


                        </tr>
                        </thead>
                        {% for student in students %}
                        <tbody>
                        <tr>
                            <td>{{ student.name }}</td>
                            <td>{{ student.id }}</td>
                            <td>{{ student.preferredName }}</td>
                            <td>{{ student.gender.gender }}</td>
                            <td>{{ student.email }}</td>
                            <td>{{ student.learningStyle.learningStyle ?? 'None'}}</td>
                            <td>{{ student.neurodiversity.neurodiversity ?? 'None' }}</td>
                            <td><a href="{{ path('display_student', {
                                    id: student.id
                                }) }}" class="text-decoration-none small" id="student-page-link">Student Page <i class="fa-solid fa-arrow-up-right-from-square"></i></a></td>

                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


            {# Phone Screen #}
            <div class="card d-block d-sm-none">
                <div class="card-header">Student Index</div>
                <div class="card-body">
                    <table class="w-100">
                        <thead>
                        <tr class="border-bottom">
                            <th scope="col">Name</th>
                            <th scope="col">Student ID</th>
                            <th scope="col"></th>


                        </tr>
                        </thead>
                        {% for student in students %}
                        <tbody>
                        <tr>
                            <td>{{ student.name }}</td>
                            <td>{{ student.id }}</td>
                            <td><a href="{{ path('display_student', {
                                    id: student.id
                                }) }}" class="text-decoration-none small" id="student-page-link">Student Page <i class="fa-solid fa-arrow-up-right-from-square"></i></a></td>

                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>






        </div>
    </div>




    {% include '/_partials/_footer.html.twig' %}


{% endblock %}

templates/display-students/displayIndividualStudent.html.twig
{% extends 'base.html.twig' %}
{% block title %}Student Information | {{ student.name }}{% endblock %}
{% block body %}
    {% include '/_partials/_header.html.twig' %}

    <div class="modal fade" id="deleteModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Student</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this student?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="" method="POST" id="deleteForm">
                        <input type="hidden" name="_method" value="DELETE">
                        <a href="{{ path('app_delete_student', {id :student.id}) }}" class="btn btn-danger" id="confirmDeleteButton">Yes</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="main-container">
        <div class="d-flex flex-wrap justify-content-between mx-auto" style="width: 80%">
            <div class="card w-75 mx-auto">
                <div class="card-header">Student Information</div>
                <div class="card-body">
                    <p><strong>Name:</strong> {{ student.name }}</p>
                    <p><strong>Preferred Name:</strong> {{ student.preferredName }}</p>
                    <p><strong>Gender:</strong> {{ student.gender.gender }}</p>
                    <p><strong>Email:</strong> {{ student.email }}</p>
                    <p><strong>Phone Number:</strong> {{ student.phoneNumber }}</p>
                    <p><strong>Date of Birth:</strong> {{ student.dateOfBirth|date('Y-m-d') }}</p>
                    <p><strong>Learning Style:</strong> {{ student.learningStyle.learningStyle ?? 'None' }}</p>
                    <p><strong>Neurodiversity:</strong> {{ student.neurodiversity.neurodiversity ?? 'None' }}</p>
                    <br>
                    <div class="d-flex flex-row">
                        {% if is_granted('ROLE_TEACHER') %}
                        <a href="{{ path('update_student', { id: student.id }) }}" class="text-decoration-none button-for-student-ud">Update</a>
                            <a role="button" data-bs-toggle="modal" data-bs-target="#deleteModal" data-student-id="{{ student.id }}" class="text-decoration-none button-for-student-ud ms-4">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include '/_partials/_footer.html.twig' %}
{% endblock %}